### ISSUE TITLE
Issue to show static and media files

### ISSUE THREAD

**Issue by JuanitoOrtega** [LondonAppDeveloper/django-docker-deployment-with-https-using-letsencrypt#1]
Please, can you make a little fix to show static and media files appropriately? I'm stuck on this part.

**Comment by valbertovc** [comment]
Hi @JuanitoOrtega.

I have a suggestion for you.

1. Adds configuration to nginx files
```nginx.conf
# docker/proxy/nginx/default.conf.tpl
# docker/proxy/nginx/default-ssl.conf.tpl

server {
    ...  

    location /static/ {
        alias /app/static/;
    }
}
```

2. Add volume in docker-compose files

```yml
# docker-compose.yml
# docker-compose.deploy.yml

services:
  proxy:
    ...
    volumes:
      ...
      - static:/app/static:ro

  app:
    ...
    volumes:
      ...
      - static:/app/static:rw

volumes:
  static:
```

3. Configure STATIC_ROOT and STATIC_URL in your Django settings file

```python
...
STATIC_URL = "static/"
STATIC_ROOT = "static"
```

4. When your container starts it must runs `python manage.py collectstatic --noinput` command.
